name: Hello Spring Boot APP to AWS EKS

on:
  workflow_dispatch:
  push:
    paths:
      - "docker/app1-hello/springboot/hello-spring"

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
           distribution: 'temurin'
           java-version: '21'
      
      - name: Build and Test (Maven)
        working-directory: docker/app1-hello/springboot/hello-spring
        run: mvn -B clean verify
      
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with: 
            name: test-reports
            path: docker/app1-hello/springboot/hello-spring/target/surefire-reports
  
  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
           distribution: 'temurin'
           java-version: '21'
      
      - name: Build Jar for Docker
        working-directory: docker/app1-hello/springboot/hello-spring
        run: mvn -B clean package -DskipTests
      
      - name: Login to Dockerhub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Docker image
        uses: docker/build-push-action@v7
        with:
          context: docker/app1-hello/springboot/hello-spring
          push: true
          tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/hello-spring:latest
              ${{ secrets.DOCKERHUB_USERNAME }}/hello-spring:${{ github.sha }}
              ${{ secrets.DOCKERHUB_USERNAME }}/hello-spring:${{ github.ref_name }}
  
  deploy-aws-eks:
    runs-on: ubuntu-latest
    needs: docker-build-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4 #This installs/configures the kubectl command on the GitHub runner.

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name hello-cluster --region ap-south-1 
        #it says Give me the Kubernetes connection configuration for the EKS cluster called hello-cluster.
        #AWS CLI then creates/updates the kubeconfig on the GitHub runner.

      - name: Verify connection
        run: kubectl get nodes

      - name: Deploy to AWS (kubernetes)
        run: kubectl apply -f k8s/aws/app1-hello 
        #Apply the Kubernetes configuration files located in k8s/aws/app1-hello.
        #So resources inside k8s/aws/app1-hello will be created/updated in your EKS cluster.